{
  "$schema": "https://json.schemastore.org/wrangler.json",
  "name": "bg-remover",
  "compatibility_date": "2026-03-22",
  "compatibility_flags": ["nodejs_compat"],

  [[d1_databases]]
  binding = "DB"
  database_name = "bgfree-db"
  database_id = "a4d77ae3-c6aa-44a3-85ae-dd1ce1c8f0ef"

  [[kv_namespaces]]
  binding = "KV"
  id = "43d5c64217f64ebcaa8a17d08ac7c310"
}
